/**
 * Стабильные машиночитаемые коды ошибок — docs/api/error-catalog.md.
 * Переименование значения = breaking change для клиентов, ловится
 * OpenAPI CI-гейтом (C-04). Значения никогда не меняются между релизами,
 * только добавляются.
 */
export enum ErrorCode {
  // Auth / Session (ADR-004)
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_NO_SESSION = 'AUTH_NO_SESSION',
  AUTH_SESSION_EXPIRED = 'AUTH_SESSION_EXPIRED',
  AUTH_SESSION_REVOKED = 'AUTH_SESSION_REVOKED',
  AUTH_AUDIENCE_MISMATCH = 'AUTH_AUDIENCE_MISMATCH',
  AUTH_2FA_REQUIRED = 'AUTH_2FA_REQUIRED',
  AUTH_RATE_LIMITED = 'AUTH_RATE_LIMITED',

  // Authorization / Tenant (ADR-002, ADR-009)
  FORBIDDEN = 'FORBIDDEN',
  ORGANIZATION_FROZEN = 'ORGANIZATION_FROZEN',
  NOT_FOUND = 'NOT_FOUND',
  ADMIN_SCOPE_INSUFFICIENT = 'ADMIN_SCOPE_INSUFFICIENT',
  ADMIN_REASON_REQUIRED = 'ADMIN_REASON_REQUIRED',
  SELF_ESCALATION_BLOCKED = 'SELF_ESCALATION_BLOCKED',
  ADMIN_SELF_DEACTIVATION_BLOCKED = 'ADMIN_SELF_DEACTIVATION_BLOCKED',
  ADMIN_LAST_SUPER_ADMIN = 'ADMIN_LAST_SUPER_ADMIN',

  // Idempotency / Concurrency (ADR-006)
  IDEMPOTENCY_KEY_REQUIRED = 'IDEMPOTENCY_KEY_REQUIRED',
  IDEMPOTENCY_KEY_CONFLICT = 'IDEMPOTENCY_KEY_CONFLICT',
  VERSION_CONFLICT = 'VERSION_CONFLICT',

  // Booking (ADR-006)
  BOOKING_OVERLAP = 'BOOKING_OVERLAP',
  BOOKING_NOT_FOUND = 'BOOKING_NOT_FOUND',
  BOOKING_INVALID_STATE_TRANSITION = 'BOOKING_INVALID_STATE_TRANSITION',

  // Unit (D-01)
  UNIT_INVALID_STATUS_TRANSITION = 'UNIT_INVALID_STATUS_TRANSITION',

  // Development (D-01) — только organization.type==='developer'
  DEVELOPMENT_REQUIRES_DEVELOPER_ORGANIZATION = 'DEVELOPMENT_REQUIRES_DEVELOPER_ORGANIZATION',

  // Publication (ADR-005)
  PUBLICATION_SOURCE_NOT_READY = 'PUBLICATION_SOURCE_NOT_READY',
  PUBLICATION_BUILD_FAILED = 'PUBLICATION_BUILD_FAILED',
  PUBLICATION_NOT_FOUND = 'PUBLICATION_NOT_FOUND',

  // Duplicate / Moderation
  DUPLICATE_DETECTED = 'DUPLICATE_DETECTED',
  DUPLICATE_OVERRIDE_REQUIRED = 'DUPLICATE_OVERRIDE_REQUIRED',

  // CRM / Contact
  CONTACT_PHONE_TAKEN = 'CONTACT_PHONE_TAKEN',

  // CRM / Library
  LIBRARY_FOLDER_NOT_EMPTY = 'LIBRARY_FOLDER_NOT_EMPTY',
  NOTIFICATION_CHANNEL_NOT_CONFIGURED = 'NOTIFICATION_CHANNEL_NOT_CONFIGURED',

  // Фиксация клиента у застройщика
  CLIENT_ALREADY_REGISTERED = 'CLIENT_ALREADY_REGISTERED',

  // Validation
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  MONEY_INVALID_CURRENCY = 'MONEY_INVALID_CURRENCY',
  MONEY_CURRENCY_MISMATCH = 'MONEY_CURRENCY_MISMATCH',
  MEDIA_MIME_MISMATCH = 'MEDIA_MIME_MISMATCH',
  MEDIA_NOT_VERIFIED = 'MEDIA_NOT_VERIFIED',

  // Rate limiting
  RATE_LIMITED = 'RATE_LIMITED',

  // Server-side
  INTERNAL_ERROR = 'INTERNAL_ERROR',
}

/**
 * HTTP-статус по умолчанию для каждого кода — может быть переопределён
 * per-endpoint через явный второй аргумент AppException, но большинство
 * случаев используют это отображение без изменений.
 */
export const ERROR_CODE_HTTP_STATUS: Record<ErrorCode, number> = {
  [ErrorCode.AUTH_INVALID_CREDENTIALS]: 401,
  [ErrorCode.AUTH_NO_SESSION]: 401,
  [ErrorCode.AUTH_SESSION_EXPIRED]: 401,
  [ErrorCode.AUTH_SESSION_REVOKED]: 401,
  [ErrorCode.AUTH_AUDIENCE_MISMATCH]: 401,
  [ErrorCode.AUTH_2FA_REQUIRED]: 401,
  [ErrorCode.AUTH_RATE_LIMITED]: 429,

  [ErrorCode.FORBIDDEN]: 403,
  [ErrorCode.ORGANIZATION_FROZEN]: 403,
  [ErrorCode.NOT_FOUND]: 404,
  [ErrorCode.ADMIN_SCOPE_INSUFFICIENT]: 403,
  [ErrorCode.ADMIN_REASON_REQUIRED]: 400,
  [ErrorCode.SELF_ESCALATION_BLOCKED]: 403,
  [ErrorCode.ADMIN_SELF_DEACTIVATION_BLOCKED]: 403,
  [ErrorCode.ADMIN_LAST_SUPER_ADMIN]: 403,

  [ErrorCode.IDEMPOTENCY_KEY_REQUIRED]: 400,
  [ErrorCode.IDEMPOTENCY_KEY_CONFLICT]: 409,
  [ErrorCode.VERSION_CONFLICT]: 409,

  [ErrorCode.BOOKING_OVERLAP]: 409,
  [ErrorCode.BOOKING_NOT_FOUND]: 404,
  [ErrorCode.BOOKING_INVALID_STATE_TRANSITION]: 409,

  [ErrorCode.UNIT_INVALID_STATUS_TRANSITION]: 409,

  [ErrorCode.DEVELOPMENT_REQUIRES_DEVELOPER_ORGANIZATION]: 403,

  [ErrorCode.PUBLICATION_SOURCE_NOT_READY]: 400,
  [ErrorCode.PUBLICATION_BUILD_FAILED]: 500,
  [ErrorCode.PUBLICATION_NOT_FOUND]: 404,

  [ErrorCode.DUPLICATE_DETECTED]: 409,
  [ErrorCode.DUPLICATE_OVERRIDE_REQUIRED]: 409,

  [ErrorCode.CONTACT_PHONE_TAKEN]: 409,
  [ErrorCode.LIBRARY_FOLDER_NOT_EMPTY]: 409,
  [ErrorCode.NOTIFICATION_CHANNEL_NOT_CONFIGURED]: 409,
  [ErrorCode.CLIENT_ALREADY_REGISTERED]: 409,

  [ErrorCode.VALIDATION_FAILED]: 400,
  [ErrorCode.MONEY_INVALID_CURRENCY]: 400,
  [ErrorCode.MONEY_CURRENCY_MISMATCH]: 400,
  [ErrorCode.MEDIA_MIME_MISMATCH]: 400,
  [ErrorCode.MEDIA_NOT_VERIFIED]: 400,

  [ErrorCode.RATE_LIMITED]: 429,

  [ErrorCode.INTERNAL_ERROR]: 500,
};
